config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "splash#index"
  resources :splash, only: [:index]
  resources :categories, only: [:index, :new, :create]
  resources :acquisition, only: [:show, :create]

  get 'acquisition/new/:id', to: 'acquisition#new', as: 'add_new_acquisition'
  post 'acquisition/create/:id', to: 'acquisition#create', as: 'create_new_acquisition'
end

app/models/acquisition.rb
class Acquisition < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories
end

app/controllers/acquisition_controller.rb
class AcquisitionController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @acquisitions = CategoryAcquisition.where(category_id: params[:id]).includes(:acquisition).order(created_at: :desc)

    sum_amount = 0

    @acquisitions.each do |item|
      sum_amount += item.acquisition.amount
    end

    @category.update(sumamount: sum_amount)
  end

  def new
    @category = params[:id]
    @acquisition = Acquisition.new
  end

  def create
    @acquisition = Acquisition.new(acquisition_params)
    @acquisition.author_id = current_user.id
    @acquisition.save

    @category_acquisition = CategoryAcquisition.new
    @category_acquisition.category_id = params[:id]
    @category_acquisition.acquisition_id = @acquisition.id
    @category_acquisition.save
    redirect_to acquisition_path(params[:id])
  end

  private

  def acquisition_params
    params.require(:acquisition).permit(:name, :amount)
  end
end

app/views/acquisition/new.html.erb
<body>
  <div class="main">
    <div class="main-register">
        <%= form_with(model: @acquisition, url: create_new_acquisition_path(@category), method: :post) do |f| %>
            <div class="signup-top-bar">
                <%= link_to acquisition_path(@category) do %>  
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 25 25" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                    </svg>
                <% end %>
                <h2>New transaction</h2>
                <%= f.submit 'Create', class: "devise-btn" %>
            </div>
        
            <div class="field">
                <%= f.text_field :name, placeholder: 'Name', :required => true %>
            </div>
            <div class="field">
                <%= f.number_field :amount, placeholder: 'Amount', :required => true, step: "0.01" %>
            </div>
        <% end %>
       </div>
  </div>
</body>  

app/views/acquisition/show.html.erb
<body>
  <div class="category-container">
    <div class="main-category">
      <div class="signup-top-bar">    
        <%= link_to root_path do %>  
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
        <% end %>
        <h2 class="top-forgot">Transactions</h2>
      </div>
      <div class="transaction-top-bar">Most recent
        <span>-</span>
      </div>
      <div class="transaction-total">
        <p>Total amount</p>    
        $ <%= @category.sumamount %>
      </div>
      <div class='category-list'>
        <% @acquisitions.each do |item| %>
            <div class="transaction-item">
              <div class="item-right">
                <div class="category-item">
                <h4><%= item.acquisition.name %></h4>
                $ <%= item.acquisition.amount %>
                </div>    
                <span><%= item.acquisition.created_at.to_date.strftime("%d %B %Y") %></span>
              </div>
            </div>    
        <% end %>
      </div>
      <footer class="category-footer">
        <%= link_to 'Add New Transaction', add_new_acquisition_path(@category.id) %>
      </footer>
    </div>
  </div>    
</body>