config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "splash#index"
  resources :splash, only: [:index]
  resources :categories, only: [:index, :new, :create]
  resources :acquisition, only: [:show, :create]

  get 'acquisition/new/:id', to: 'acquisition#new', as: 'add_new_acquisition'
  post 'acquisition/create/:id', to: 'acquisition#create', as: 'create_new_acquisition'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :acquisitions
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(user_id: current_user.id)
    @current_user = current_user
  end

  def new
    @category = Category.new
    @owner = current_user
  end

  def create
    @category_info = Category.new(new_category_params)
    @category_info.user_id = current_user.id

    if @category_info.save
      flash[:notice] = 'The category was created successfully!'
    else
      flash[:alert] = 'The category could not be created!'
    end
    redirect_to categories_path
  end

  private

  def new_category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/views/categories/index.html.erb
<body>
  <div class="category-container">
    <div class="main-category">
      <div class="signup-top-bar">
        <%= link_to root_path do %>  
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 25 25" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
        <% end %>
        <h2 >Categories</h2>
        <%= render "partials/signout" %>
      </div>
      <div class='category-list'>
        <% @categories.each do |category| %>
            <%= link_to acquisition_path(category.id) do %>
              <div class="category-icon"> 
                <img src="<%=category.icon%>" alt="Category icon" width="50" height="50"></img>
              </div>
              <div class="item-right">
                <div class="category-item">
                  <h4><%= category.name %></h4>
                  $ <%= category.sumamount %>
                </div>    
                <span><%= category.updated_at.to_date.strftime("%d %B %Y") %></span>
              </div>  
            <% end %>        
        <% end %>
      </div>
      <footer class="category-footer">
        <%= link_to "Add a New Category", new_category_path %>
      </footer>
    </div>
  </div>  
</body>

app/views/categories/new.html.erb
<body>
  <div class="main">
    <div class="main-register">
      <%= form_with(model: @category, url: categories_path, method: :post) do |f| %>
        <div class="signup-top-bar">
          <%= link_to root_path do %>  
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 25 25" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
          <% end %>
          <h2>New Category</h2>
          <%= f.submit 'Create', class: "devise-btn" %>
        </div>
        <div class="field">
          <%= f.text_field :name, placeholder: 'Name', required: true %>
        </div>

        <div class="field">
          <%= f.url_field :icon, placeholder: 'Icon image URL', required: true %>
        </div>
      <% end %>
    </div>
  </div>
</body>  